name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"      # run on every branch
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Run tests with coverage
    - name: Run tests with coverage
      run: |
        PYTHONPATH=. pytest --cov=aceest_fitness --cov-report=xml --cov-report=term-missing

    # Upload coverage to Codecov (optional, works only if you enable Codecov)
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t aceest_fitness .
